timesteps : 1000

device : cuda

img_path : ./imgs
save_path : ./save
image_width : 192
image_height : 128
batch_size : 32
shuffle : True
pin_memory : False
num_workers : 0

# For sampling the model
sampling_steps : 500
ddim : False

epochs : 1000
lr : 1e-4

in_channels : 3
out_channels : 3
num_channels : 3
base_width : 32
num_res_blocks : 4
attention_resolutions : [32, 16, 8]
channel_mult : [1, 1, 2, 3, 4, 8]
conv_resample : True
dims : 2
num_heads_upsample : -1
num_heads : 4
num_head_channels : 32
dropout : 0.1
use_checkpoint : True
use_fp16 : False
time_emb_factor : 2
use_scale_shift_norm : True
resblock_updown : True
use_new_attention_order : True
class_cond : True

local_rank : 0
ema_w : 0.9995

img_every : 20
save_every : 40
use_trained : True
saved_model_name : u_net
# saved_model_name : u_net_2k
