APP_CONFIG:
  name : YouTube Api Dashboard

CACHE_CONFIG:
  DEBUG : TRUE
  CACHE_TYPE : SimpleCache
  CACHE_DEFAULT_TIMEOUT : 600

PATHS:
  DF : https://squeemos.pythonanywhere.com/static/yt_trending.xz
  CATEGORIES : https://squeemos.pythonanywhere.com/static/video_categories.json

LOCAL : TRUE
