APP_CONFIG:
  name : YouTube Api Dashboard

CACHE_CONFIG:
  DEBUG : TRUE
  CACHE_TYPE : SimpleCache
  CACHE_DEFAULT_TIMEOUT : 600

PATHS:
  TRENDING : https://squeemos.pythonanywhere.com/static/yt_trending.feather
  CATEGORIES : https://squeemos.pythonanywhere.com/static/yt_categories.feather
  CATEGORY_IDS : https://squeemos.pythonanywhere.com/static/video_categories.json

LOCAL : FALSE
