APP_CONFIG:
  suppress_callback_exceptions : True

CACHE_CONFIG:
  DEBUG : True
  CACHE_TYPE : FileSystemCache
  CACHE_DEFAULT_TIMEOUT : 600
  CACHE_DIR : dev/shm

PATHS:
  TRENDING : https://squeemos.pythonanywhere.com/static/yt_trending.feather
  CATEGORIES : https://squeemos.pythonanywhere.com/static/yt_categories.feather
  CATEGORY_IDS : https://squeemos.pythonanywhere.com/static/video_categories.json

LOCAL : False
